"""Final held-out analysis for the NodeX r6 optimization.
usage: python bench/final/final_analysis.py <out.md> <summary.json>
Reads bench/results/final/*.jsonl (A, B, C_*, D) and the NFEI json produced by
bench/final/nfei-score.mjs (bench/results/final/nfei_scores.json).
"""
import json, math, sys, os, statistics as st
from collections import defaultdict

R = "bench/results/final/"
OUT_MD, OUT_JSON = sys.argv[1], sys.argv[2]
T975 = {1: 12.706, 2: 4.303, 3: 3.182, 4: 2.776, 5: 2.571, 6: 2.447, 7: 2.365, 8: 2.306, 9: 2.262, 10: 2.228,
        11: 2.201, 12: 2.179, 13: 2.160, 14: 2.145, 15: 2.131, 16: 2.120, 17: 2.110, 18: 2.101, 19: 2.093, 20: 2.086,
        25: 2.060, 30: 2.042, 40: 2.021, 60: 2.000, 120: 1.980}
def tcrit(df):
    ks = sorted(T975)
    for k in ks:
        if df <= k: return T975[k]
    return 1.96

def load(f):
    p = R + f
    if not os.path.exists(p): return []
    return [json.loads(l) for l in open(p) if l.strip()]

def m(x):
    r = x["record"]; p = r["performance"]; am = r["architectureMetrics"]; ph = am.get("physics") or {}
    al = am.get("allocation") or {}; t = x["telemetry"]
    done = p.get("tasksCompleted") or 0; tot = p.get("tasksTotal") or 0
    alldone = x["end_reason"] == "ALL_TASKS_COMPLETE" and p.get("completionTimeSeconds") is not None
    tobs = p["completionTimeSeconds"] if alldone else p["simTimeSeconds"]
    return dict(
        sys=x["system"], sc=x["scenario"], n=x["fleet_size"], seed=x["seed"], src=x["src"], id=x["run_id"],
        done=done, tot=tot, alldone=alldone, tobs=tobs,
        thr=done * 3600 / tobs if tobs else 0.0,
        donepct=100 * done / tot if tot else None,
        mk=p["completionTimeSeconds"] if alldone else None,
        cyc=al.get("taskCompletionAvgS"), wait=t.get("waiting_fraction_of_busy"), stops=t.get("stops_per_robot"),
        mpt=t.get("messages_per_completed_task"), kbpt=(t.get("bytes_per_completed_task") or 0) / 1024 if t.get("bytes_per_completed_task") is not None else None,
        lat=al.get("allocationLatencyAvgS"), near=t.get("near_collision_events"), sep=t.get("min_separation_px_moving"),
        sepall=t.get("min_separation_px_all"), npt=(t.get("near_collision_events") or 0) / done if done else None,
        coll=ph.get("collisions", 0) or 0, intr=ph.get("obstacleIntrusions", 0) or 0, bnd=ph.get("boundaryViolations", 0) or 0,
        contact=t.get("contact_events", 0) or 0, cpu=(t.get("cpu_ms_per_tick") or {}).get("mean") if isinstance(t.get("cpu_ms_per_tick"), dict) else t.get("cpu_ms_per_tick"), verdict=x.get("verdict"), wall=x.get("wall_s"))

def mean(v):
    v = [a for a in v if a is not None]
    return st.mean(v) if v else None
def f(v, d=1):
    if v is None: return "–"
    if isinstance(v, float) and abs(v) >= 1000: return f"{v:,.0f}"
    return f"{v:.{d}f}"

def outcome(a, b):
    """Baseline-summary rule: more tasks completed wins, then shorter observed time (1 % band)."""
    if a["done"] != b["done"]: return 1 if a["done"] > b["done"] else -1
    if a["alldone"] and b["alldone"]:
        if a["tobs"] < b["tobs"] * 0.99: return 1
        if b["tobs"] < a["tobs"] * 0.99: return -1
    return 0

def geo_ci(ratios):
    lr = [math.log(r) for r in ratios if r and r > 0]
    k = len(lr)
    if k == 0: return None, None, None, 0
    g = math.exp(st.mean(lr))
    if k < 2: return g, None, None, k
    se = st.stdev(lr) / math.sqrt(k); h = tcrit(k - 1) * se
    return g, math.exp(st.mean(lr) - h), math.exp(st.mean(lr) + h), k

A = [m(x) for x in load("A_src_all.jsonl")]
B = [m(x) for x in load("B_before.jsonl")]
ABL = {"all": [r for r in B if r["sys"] == "ace" and r["n"] in (10, 50)], **{name: [m(x) for x in load(f"C_{name}.jsonl")] for name in ["ws1", "ws2", "ws3"]}}
D = load("D_acetests.jsonl"); DB = [json.loads(l) for l in open("bench/results/baseline_acetests.jsonl") if l.strip()]
nf = {}
if os.path.exists(R + "nfei_scores.json"):
    for s in json.load(open(R + "nfei_scores.json")): nf[s["run_id"]] = s
for r in A + B:
    s = nf.get(r["id"]); r["nfei"] = s["nfei"] if s else None

FLEETS = [3, 10, 50, 100]; SYS = ["centralized", "decentralized", "ace"]
SCN = ["S01", "S03", "S06", "S07", "S08", "S09", "S13"]
SCN_NAME = {"S01": "normal", "S03": "congestion", "S06": "comm delay", "S07": "comm loss", "S08": "robot failure", "S09": "deadlock", "S13": "combined"}
idx = defaultdict(dict)
for r in A: idx[(r["sc"], r["n"], r["seed"])][r["sys"]] = r
summary = {"n_runs": {"A": len(A), "B": len(B), **{f"C_{k}": len(v) for k, v in ABL.items()}, "D": len(D)}}
L = []
P = L.append
P("# NodeX: baseline vs optimized — held-out final test results\n")
P("Generated by `bench/final/final_analysis.py` (NFEI via `bench/final/nfei-score.mjs` → `src/data/nfei.js` v2.1). "
  "Config `NODEX-ARCH-2026.09-r6-bigmap`, held-out seeds **3, 4** (never used in development), scenarios "
  + ", ".join(f"{s} {SCN_NAME[s]}" for s in SCN) + ", fleets 3/10/50/100, timeline `scenario`.\n")
P("Data files (all in `bench/results/final/`): `A_src_all.jsonl` (src, 3 systems), `B_before.jsonl` "
  "(src with NODEX_ABLATE=all = pre-optimization behaviour, all 3 systems), `C_ws1|ws2|ws3.jsonl` (ablations on src; ablation \"all\" = ACE rows of B_before), `D_acetests.jsonl` (ACE tests), `nfei_scores.json`.\n")
P(f"Run counts: {summary['n_runs']}.\n")
P("Throughput = tasks completed × 3600 / T_obs (T_obs = makespan if all tasks completed, else sim time at the duration limit). "
  "Win/loss rule (same as `BASELINE_SUMMARY.md`): more tasks completed wins, then shorter completion time (1 % band), else tie. "
  "Geo-mean ratios: exp(mean log ratio) over paired runs, 95 % CI = t-interval on the paired log ratios.\n")

COLS = [("Runs", None), ("All done", "alldone"), ("Tasks done %", "donepct"), ("Thr /h", "thr"), ("Makespan s*", "mk"), ("Cycle s", "cyc"),
        ("Wait frac (busy)", "wait"), ("Stops/robot", "stops"), ("Msgs/task", "mpt"), ("KB/task", "kbpt"), ("Alloc lat s", "lat"),
        ("Near-coll.", "near"), ("Near/task", "npt"), ("Min sep moving px", "sep"), ("Coll.", "coll"), ("Intrus.", "intr"), ("CPU ms/tick", "cpu"), ("NFEI v2.1", "nfei")]
def row(rs):
    out = []
    for name, k in COLS:
        if k is None: out.append(str(len(rs)))
        elif k == "alldone": out.append(f"{sum(r['alldone'] for r in rs)}/{len(rs)}")
        elif k in ("coll", "intr"): out.append(str(sum(r[k] for r in rs)))
        elif k == "sep": v = [r[k] for r in rs if r[k] is not None]; out.append(f(min(v)) if v else "–")
        elif k in ("wait",): out.append(f(mean([r[k] for r in rs]), 2))
        elif k in ("cpu",): out.append(f(mean([r[k] for r in rs]), 2))
        else: out.append(f(mean([r[k] for r in rs]), 1))
    return out
def hdr(first):
    P("| " + " | ".join(first + [c[0] for c in COLS]) + " |"); P("|" + "---|" * (len(first) + len(COLS)))

P("\n## 1. Three systems by fleet size (src, all 7 scenarios × 2 seeds pooled)\n")
P("*Makespan averaged over runs that completed all tasks only. Min sep = minimum over runs.\n")
hdr(["Fleet", "System"])
summary["by_fleet"] = {}
for n in FLEETS:
    for s in SYS:
        rs = [r for r in A if r["n"] == n and r["sys"] == s]
        if rs: P("| " + " | ".join([str(n), s] + row(rs)) + " |")
        summary["by_fleet"][f"{n}|{s}"] = dict(thr=mean([r["thr"] for r in rs]), donepct=mean([r["donepct"] for r in rs]), near=mean([r["near"] for r in rs]),
                                               nfei=mean([r["nfei"] for r in rs]), mpt=mean([r["mpt"] for r in rs]), cpu=mean([r["cpu"] for r in rs]), runs=len(rs))

P("\n## 2. Three systems by scenario (src, fleets 3/10/50/100 × 2 seeds pooled)\n")
hdr(["Scenario", "System"])
for sc in SCN:
    for s in SYS:
        rs = [r for r in A if r["sc"] == sc and r["sys"] == s]
        if rs: P("| " + " | ".join([f"{sc} {SCN_NAME[sc]}", s] + row(rs)) + " |")

def paired(filter_fn, other):
    w = l = t = 0; rat = []
    for key, g in idx.items():
        if not filter_fn(key) or "ace" not in g or other not in g: continue
        o = outcome(g["ace"], g[other]); w += o == 1; l += o == -1; t += o == 0
        if g["ace"]["thr"] > 0 and g[other]["thr"] > 0: rat.append(g["ace"]["thr"] / g[other]["thr"])
    return w, l, t, geo_ci(rat), len(rat)
def ci_s(c):
    g, lo, hi, k = c
    if g is None: return "–"
    return f"{g:.2f} [{lo:.2f}, {hi:.2f}]" if lo else f"{g:.2f}"

P("\n## 3. Paired comparison: NodeX ACE vs centralized / decentralized (src)\n")
P("| Group | n pairs | ACE vs central W/L/T | Thr ratio ACE/central geo [95 % CI] | ACE vs decentral W/L/T | Thr ratio ACE/decentral geo [95 % CI] |")
P("|---|---|---|---|---|---|")
summary["paired"] = {}
groups = [(f"fleet {n}", (lambda k, n=n: k[1] == n)) for n in FLEETS] + [(f"{sc} {SCN_NAME[sc]}", (lambda k, sc=sc: k[0] == sc)) for sc in SCN] + [("all", lambda k: True)]
for name, fn in groups:
    wc, lc, tc, cc, kc = paired(fn, "centralized"); wd, ld, td, cd, kd = paired(fn, "decentralized")
    P(f"| {name} | {kc} | {wc}/{lc}/{tc} | {ci_s(cc)} | {wd}/{ld}/{td} | {ci_s(cd)} |")
    summary["paired"][name] = dict(vsC=[wc, lc, tc, cc[0], cc[1], cc[2]], vsD=[wd, ld, td, cd[0], cd[1], cd[2]], n=kc)

P("\n### 3.1 Throughput (tasks/h) per scenario × fleet, mean of seeds 3, 4 (C / D / ACE)\n")
P("| Scenario | " + " | ".join(f"fleet {n}" for n in FLEETS) + " |"); P("|---|" + "---|" * len(FLEETS))
for sc in SCN:
    cells = []
    for n in FLEETS:
        v = [mean([r["thr"] for r in A if r["sc"] == sc and r["n"] == n and r["sys"] == s]) for s in SYS]
        cells.append(" / ".join(f(x, 0) for x in v))
    P(f"| {sc} {SCN_NAME[sc]} | " + " | ".join(cells) + " |")

P("\n## 4. NFEI v2.1 (0-100, 100 = best KPI in the paired group; project-specific composite, not a standard)\n")
P("Mean NFEI over the scored runs; reference = best of the 3 systems in the same (scenario, fleet, seed, config, tree). Before-runs (B) are scored in their own groups.\n")
P("| Fleet | centralized | decentralized | ace | ACE highest NFEI in (runs) |"); P("|---|---|---|---|---|")
summary["nfei"] = {}
for n in FLEETS + ["all"]:
    vals = {s: mean([r["nfei"] for r in A if (n == "all" or r["n"] == n) and r["sys"] == s]) for s in SYS}
    top = 0; tot = 0
    for key, g in idx.items():
        if n != "all" and key[1] != n: continue
        if all(s in g and g[s]["nfei"] is not None for s in SYS):
            tot += 1; top += g["ace"]["nfei"] >= max(g["centralized"]["nfei"], g["decentralized"]["nfei"])
    P(f"| {n} | {f(vals['centralized'])} | {f(vals['decentralized'])} | {f(vals['ace'])} | {top}/{tot} |")
    summary["nfei"][str(n)] = dict(vals, top=[top, tot])

# Before vs after
P("\n## 5. Before (NODEX_ABLATE=all) vs after (all switches on), same src tree, map, workload, seeds\n")
bidx = {(r["sys"], r["sc"], r["n"], r["seed"]): r for r in B}
P("| System | Fleet | n pairs | Thr before | Thr after | Geo ratio after/before [95 % CI] | W/L/T after vs before | Done % before → after | Near-coll before → after | Msgs/task before → after | CPU ms/tick before → after |")
P("|---|---|---|---|---|---|---|---|---|---|---|")
summary["before_after"] = {}
for s in SYS:
    for n in FLEETS:
        pairs = [(bidx[(s, r["sc"], r["n"], r["seed"])], r) for r in A if r["sys"] == s and r["n"] == n and (s, r["sc"], r["n"], r["seed"]) in bidx]
        if not pairs: continue
        b = [p[0] for p in pairs]; a = [p[1] for p in pairs]
        c = geo_ci([y["thr"] / x["thr"] for x, y in pairs if x["thr"] > 0 and y["thr"] > 0])
        o = [outcome(y, x) for x, y in pairs]
        P(f"| {s} | {n} | {len(pairs)} | {f(mean([x['thr'] for x in b]),0)} | {f(mean([x['thr'] for x in a]),0)} | {ci_s(c)} | {o.count(1)}/{o.count(-1)}/{o.count(0)} | "
          f"{f(mean([x['donepct'] for x in b]))} → {f(mean([x['donepct'] for x in a]))} | {f(mean([x['near'] for x in b]))} → {f(mean([x['near'] for x in a]))} | "
          f"{f(mean([x['mpt'] for x in b]),0)} → {f(mean([x['mpt'] for x in a]),0)} | {f(mean([x['cpu'] for x in b]),2)} → {f(mean([x['cpu'] for x in a]),2)} |")
        summary["before_after"][f"{s}|{n}"] = dict(n=len(pairs), before=mean([x['thr'] for x in b]), after=mean([x['thr'] for x in a]), geo=c[:3], wlt=[o.count(1), o.count(-1), o.count(0)],
                                                    near=[mean([x['near'] for x in b]), mean([x['near'] for x in a])])

P("\n### 5.1 NodeX vs baselines, before and after\n")
P("before = all switches off in all three systems (no ws* optimizations, no fix-* bug fixes); after = all on.\n")
P("| Fleet | Tree | n | ACE vs C W/L/T | ACE/C geo [95 % CI] | ACE vs D W/L/T | ACE/D geo [95 % CI] |"); P("|---|---|---|---|---|---|---|")
for n in FLEETS:
    for tree, pool in (("before", bidx), ("after", {(r["sys"], r["sc"], r["n"], r["seed"]): r for r in A})):
        res = []
        for o_s in ("centralized", "decentralized"):
            w = l = t = 0; rat = []
            for (s, sc, nn, sd), r in pool.items():
                if s != "ace" or nn != n or (o_s, sc, nn, sd) not in pool: continue
                q = pool[(o_s, sc, nn, sd)]; o = outcome(r, q); w += o == 1; l += o == -1; t += o == 0
                if r["thr"] > 0 and q["thr"] > 0: rat.append(r["thr"] / q["thr"])
            res.append((w, l, t, geo_ci(rat), len(rat)))
        P(f"| {n} | {tree} | {res[0][4]} | {res[0][0]}/{res[0][1]}/{res[0][2]} | {ci_s(res[0][3])} | {res[1][0]}/{res[1][1]}/{res[1][2]} | {ci_s(res[1][3])} |")

# Ablation
P("\n## 6. Ablation (src, ACE only, NODEX_ABLATE, fleets 10 and 50, 7 scenarios × seeds 3, 4)\n")
P("Ratio = geo-mean paired throughput of the ablated run / full src ACE run (< 1 ⇒ the disabled group contributed).\n")
aidx = {(r["sc"], r["n"], r["seed"]): r for r in A if r["sys"] == "ace"}
P("| Disabled | Fleet | n | Thr full | Thr ablated | Geo ratio ablated/full [95 % CI] | Tasks done % ablated | Near-coll ablated (full) | Msgs/task ablated (full) |")
P("|---|---|---|---|---|---|---|---|---|")
summary["ablation"] = {}
for name, rs in ABL.items():
    for n in FLEETS:
        pairs = [(aidx[(r["sc"], r["n"], r["seed"])], r) for r in rs if r["n"] == n and (r["sc"], r["n"], r["seed"]) in aidx]
        if not pairs: continue
        c = geo_ci([y["thr"] / x["thr"] for x, y in pairs if x["thr"] > 0 and y["thr"] > 0])
        P(f"| {name} | {n} | {len(pairs)} | {f(mean([x['thr'] for x,_ in pairs]),0)} | {f(mean([y['thr'] for _,y in pairs]),0)} | {ci_s(c)} | {f(mean([y['donepct'] for _,y in pairs]))} | "
          f"{f(mean([y['near'] for _,y in pairs]))} ({f(mean([x['near'] for x,_ in pairs]))}) | {f(mean([y['mpt'] for _,y in pairs]),0)} ({f(mean([x['mpt'] for x,_ in pairs]),0)}) |")
        summary["ablation"][f"{name}|{n}"] = dict(n=len(pairs), geo=c[:3])

# Safety
P("\n## 7. Safety (all final runs)\n")
P("| Set | Runs | Collisions | Obstacle intrusions | Boundary violations | Contact events | Min sep moving px (min) | Near-coll. total |"); P("|---|---|---|---|---|---|---|---|")
summary["safety"] = {}
for name, rs in [("A src " + s, [r for r in A if r["sys"] == s]) for s in SYS] + [("B before " + s, [r for r in B if r["sys"] == s]) for s in SYS] + [(f"C ablate {k}", v) for k, v in ABL.items() if k != "all"]:
    if not rs: continue
    sep = [r["sep"] for r in rs if r["sep"] is not None]
    vals = [sum(r[k] for r in rs) for k in ("coll", "intr", "bnd", "contact")]
    P(f"| {name} | {len(rs)} | " + " | ".join(map(str, vals)) + f" | {f(min(sep)) if sep else '–'} | {sum((r['near'] or 0) for r in rs)} |")
    summary["safety"][name] = vals

# ACE tests
P("\n## 8. ACE validation tests A01-A12 (src vs baseline, seed 18427)\n")
bt = {(x["scenario"], x["fleet_size"]): x for x in DB if x["seed"] == 18427}
P("| Test | Fleet | Baseline verdict | src verdict | Tasks base → src |"); P("|---|---|---|---|---|")
cnt = defaultdict(int); fails = []
for x in sorted(D, key=lambda x: (x["fleet_size"], x["scenario"])):
    b = bt.get((x["scenario"], x["fleet_size"]))
    pb = b["record"]["performance"] if b else None; pa = x["record"]["performance"]
    cnt[x["verdict"]] += 1
    if x["verdict"] != "PASS": fails.append(f"{x['scenario']}/{x['fleet_size']} {x['verdict']}")
    P(f"| {x['scenario']} | {x['fleet_size']} | {b['verdict'] if b else '–'} | {x['verdict']} | {pb['tasksCompleted'] if pb else '–'}/{pb['tasksTotal'] if pb else '–'} → {pa['tasksCompleted']}/{pa['tasksTotal']} |")
P(f"\nsrc verdicts: {dict(cnt)}; non-PASS: {', '.join(fails) or 'none'}. Baseline (fleets 3,10): "
  + str({v: sum(1 for x in DB if x['seed'] == 18427 and x['fleet_size'] in (3, 10) and x['verdict'] == v) for v in set(x['verdict'] for x in DB)}) + "\n")
summary["acetests"] = dict(cnt=dict(cnt), fails=fails)

# CPU
P("\n## 9. Computational cost (mean CPU ms/tick, 10 shards in parallel — relative only)\n")
P("| Fleet | " + " | ".join(SYS) + " | before C | before D | before ace |"); P("|---|---|---|---|---|---|---|")
for n in FLEETS:
    P(f"| {n} | " + " | ".join(f(mean([r['cpu'] for r in A if r['n'] == n and r['sys'] == s]), 2) for s in SYS) + " | " + " | ".join(f(mean([r['cpu'] for r in B if r['n'] == n and r['sys'] == s]), 2) for s in SYS) + " |")

open(OUT_MD, "w", encoding="utf-8").write("\n".join(L) + "\n")
json.dump(summary, open(OUT_JSON, "w"), indent=1, default=str)
print("ok", summary["n_runs"])
